### ISSUE TITLE
returning no commit found

### ISSUE THREAD

**Issue by Honelign** [apappas1129/git-synced#1] opened 2024-11-26 08:26 UTC
I saved the github page of my second profile as html and run the code and it responded no commit found is there a specific way on how I download the profile page?

**Comment by apappas1129** [comment] 2024-11-28 08:42
I tried both directly saving the page and manually copying the entire html from the devtools and they both worked. make sure the your contributions graph is rendered and contains commits.

**Comment by apappas1129** [comment] 2024-11-28 08:48
Clarificatio on:

> and it responded no commit found

What is the exact error/log printed?

Is it this

https://github.com/apappas1129/git-synced/blob/a23dffc0843ccedee4b62822e9c7a98d92a01fcf/index.js#L125

, or this?

https://github.com/apappas1129/git-synced/blob/a23dffc0843ccedee4b62822e9c7a98d92a01fcf/index.js#L201

**Comment by MobCode100** [comment] 2024-12-02 02:44
It's both. I'm also having the same issue.

![test](https://github.com/user-attachments/assets/550478d9-35d2-46ee-b2ba-6534e61056e9)

**Comment by apappas1129** [comment] 2024-12-02 04:29
please send a shareable link of your html files. will try it on my end and compare with what I have.

**Comment by MobCode100** [comment] 2024-12-02 04:59
[index.zip](https://github.com/user-attachments/files/17972724/index.zip)

**Comment by apappas1129** [comment] 2024-12-02 06:04
> [index.zip](https://github.com/user-attachments/files/17972724/index.zip)

it doesn't contain a contribution graph:

![image](https://github.com/user-attachments/assets/799e6112-e5a8-44e2-a45b-1fe00ec61492)

**Comment by MobCode100** [comment] 2024-12-02 06:20
I see, i think the saved html format was faulty.

**Comment by apappas1129** [comment] 2024-12-03 01:56
> I see, i think the saved html format was faulty.

make sure to save your profile page with the contributions graph rendered. it doesn't matter if the CSS is broken when you open your html file to view it. As long as the contribution graph is in the DOM and the selectors used in `git-synced`'s script are not outdated, it should be fine.

**Comment by apappas1129** [comment] 2024-12-03 01:57
I will keep this issue alive for a short while to wait for @Honelign 's input.

**Comment by MobCode100** [comment] 2024-12-03 02:10
> > I see, i think the saved html format was faulty.
> 
> make sure to save your profile page with the contributions graph rendered. it doesn't matter if the CSS is broken when you open your html file to view it. As long as the contribution graph is in the DOM and the selectors used in `git-synced`'s script are not outdated, it should be fine.

Maybe we can put some note/warning so that people can expect this error?

**Comment by apappas1129** [comment] 2024-12-03 06:26
> > > I see, i think the saved html format was faulty.
> > 
> > 
> > make sure to save your profile page with the contributions graph rendered. it doesn't matter if the CSS is broken when you open your html file to view it. As long as the contribution graph is in the DOM and the selectors used in `git-synced`'s script are not outdated, it should be fine.
> 
> Maybe we can put some note/warning so that people can expect this error?

I believe this should be sufficient:
https://github.com/apappas1129/git-synced/blob/a23dffc0843ccedee4b62822e9c7a98d92a01fcf/README.md?plain=1#L19

But I'll consider elaborating. thank you

**Comment by apappas1129** [comment] 2024-12-03 06:30
@Honelign It appears that the problem is not in the tool itself but rather due to a configuration or usage issue. Please feel free to reach out if you need further guidance or clarification. Closing this issue for now.

**Closed as completed by apappas1129** 2024-12-03 06:30 UTC

**Comment by MobCode100** [comment] 2024-12-03 06:35
> But I'll consider elaborating. thank you

Maybe put a specific mention to the `html` file, so people too will check the saved html file. That would be enough I think.

**Comment by Honelign** [comment] 2024-12-03 07:40
yes worked for me it was a usage issue

**Comment by apappas1129** [comment] 2024-12-11 00:15
@MobCode100 Will be glad to get a PR with your suggested docs improvement.
